name: canto-store

services:
  - name: web
    source_dir: /apps/web
    github:
      repo: canto-store/canto
      branch: main
    run_command: node apps/web/server.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    environments:
      - name: UPLOADTHING_TOKEN
        value: ${UPLOADTHING_TOKEN}
      - name: SPACES_KEY
        value: ${SPACES_KEY}
      - name: SPACES_SECRET
        value: ${SPACES_SECRET}
      - name: SPACES_REGION
        value: ${SPACES_REGION}
      - name: SPACES_BUCKET
        value: ${SPACES_BUCKET}
      - name: NODE_ENV
        value: 'production'
      - name: NEXT_TELEMETRY_DISABLED
        value: '1'
      - name: PORT
        value: '3000'
      - name: HOSTNAME
        value: '0.0.0.0'

  - name: server
    source_dir: /apps/server
    github:
      repo: canto-store/canto
      branch: main
    run_command: node build/src/index.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    environments:
      - name: DATABASE_URL
        value: ${DATABASE_URL}
      - name: ELASTICSEARCH_NODE
        value: ${ELASTICSEARCH_NODE}
      - name: ELASTICSEARCH_USERNAME
        value: ${ELASTICSEARCH_USERNAME}
      - name: ELASTICSEARCH_PASSWORD
        value: ${ELASTICSEARCH_PASSWORD}
      - name: DELIVERIC_API
        value: ${DELIVERIC_API}
      - name: DELIVERIC_USER
        value: ${DELIVERIC_USER}
      - name: DELIVERIC_PASSWORD
        value: ${DELIVERIC_PASSWORD}
      - name: NODE_ENV
        value: 'production'
      - name: PORT
        value: '8000'

  - name: dashboard
    source_dir: /apps/dashboard
    github:
      repo: canto-store/canto
      branch: main
    run_command: serve -s dist -l 5173
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 5173
    environments:
      - name: NODE_ENV
        value: 'production'
      - name: PORT
        value: '5173'
