name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build, Push & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "soubky0" --password-stdin

      - name: Build & Push
        run: |
          docker build -t ghcr.io/canto-store/canto-frontend-v2:latest .
          docker push ghcr.io/canto-store/canto-frontend-v2:latest

      - name: Deploy on Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ghcr.io/soubky0/canto-frontend-v2:latest
            docker stop canto-frontend-v2 || true
            docker rm canto-frontend-v2 || true
            docker run -d \
              --name canto-frontend-v2 \
              -p 3030:3030 \
              --restart unless-stopped \
              ghcr.io/soubky0/canto-frontend-v2:latest
