name: CD

on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"

permissions:
  contents: read
  packages: write

jobs:
  deploy_application:
    name: Build, Publish, and Deploy Next.js App
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Application Version
        id: extract_version
        run: echo "version=$(node -p "require('./apps/web/package.json').version")" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Publish Docker Image
        uses: useblacksmith/build-push-action@v1
        with:
          image: ghcr.io/${{ github.repository }}-web
          tags: |
            v${{ steps.extract_version.outputs.version }}
            latest
          context: ./apps/web
          secrets: |
            "UPLOADTHING_TOKEN=${{ secrets.UPLOADTHING_TOKEN }}"

      - name: Deploy Application to Production Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            IMAGE_REFERENCE="ghcr.io/${{ github.repository }}-web:latest"
            CONTAINER_NAME="${{ github.event.repository.name }}-web"
            APP_EXTERNAL_PORT="3000"
            APP_INTERNAL_PORT="3000"

            echo "Pulling latest image: $IMAGE_REFERENCE"
            docker pull $IMAGE_REFERENCE

            echo "Stopping existing container (if any): $CONTAINER_NAME"
            docker stop $CONTAINER_NAME || true

            echo "Removing existing container (if any): $CONTAINER_NAME"
            docker rm $CONTAINER_NAME || true

            echo "Starting new container: $CONTAINER_NAME"
            docker run -d \
              --name $CONTAINER_NAME \
              -p $APP_EXTERNAL_PORT:$APP_INTERNAL_PORT \
              --restart unless-stopped \
              -e UPLOADTHING_TOKEN=${{ secrets.UPLOADTHING_TOKEN }} \
              $IMAGE_REFERENCE
